// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fejtttugmmiwdnabjrzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlanR0dHVnbW1pd2RuYWJqcnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTEwOTEsImV4cCI6MjA3Mzc2NzA5MX0.Z12t9asLN2FThBThYE8i4CNg90JORZQspfXh0cNONuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});